# -*- coding: utf-8 -*-
"""uc.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NE0PZcU2Jx0RD3J-KaLYoOV0ufaCJBV_
"""
from flask import Flask, request, jsonify
import sqlite3
import os

app = Flask(__name__)
DB_NAME = "memory.db"

def init_db():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS addition_memory (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        num1 INTEGER,
        num2 INTEGER,
        result INTEGER
    )
    """)
    conn.commit()
    conn.close()

def add_number(a, b):
    return a + b

@app.route("/add", methods=["POST"])
def add_api():
    data = request.get_json()

    num1 = data.get("num1")
    num2 = data.get("num2")

    result = add_number(num1, num2)

    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO addition_memory (num1, num2, result) VALUES (?, ?, ?)",
        (num1, num2, result)
    )
    conn.commit()
    conn.close()

    return jsonify({
        "num1": num1,
        "num2": num2,
        "sum": result,
        "message": "Result saved in SQLite memory"
    })

if __name__ == "__main__":
    init_db()
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)



 
